language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.1.8
  - 2.2.5
  - 2.3.3
before_install:
- rvm @global do gem uninstall -aIx bundler
- rvm @global do gem install bundler -v 1.10.6
script: bundle exec rake